title: Van Rachna
logo: /asset/images/Van_Rachna.png
# description: Hellow World 
show_downloads: true
theme: jekyll-theme-minimal

# Personalize the colours in your website. Colour values can be any valid CSS colour
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

plugins:
  - jekyll-paginate
  - jekyll-sitemap

  #####################################
# --- Footer social media links --- #
#####################################

# Select the social network links that you want to show in the footer.
# You can change the order that they show up on the page by changing the order here.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: "someone@example.com"
  rss: true  # remove this line if you don't want to show an RSS link at the bottom
  facebook: deanattali
  github: daattali
  twitter: daattali
  patreon: DeanAttali
  youtube: "@daattali"
  whatsapp: 15551212
